- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Additional collection of iptables, netstat and CNI configuration.
Tested on Ubuntu 18.04 and CentOS 7.6
```
../networking# ls -lah
total 296K
drwxr-xr-x 2 root root 4.0K Nov 26 07:03 .
drwx------ 9 root root 4.0K Nov 26 07:03 ..
-rw-r--r-- 1 root root  602 Nov 26 07:03 cni-config
-rw-r--r-- 1 root root  11K Nov 26 07:03 ifconfiga
-rw-r--r-- 1 root root 7.3K Nov 26 07:03 ipaddrshow
-rw-r--r-- 1 root root 1.2K Nov 26 07:03 iproute
-rw-r--r-- 1 root root  96K Nov 26 07:03 iptables
-rw-r--r-- 1 root root 2.8K Nov 26 07:03 iptablesmangle
-rw-r--r-- 1 root root  22K Nov 26 07:03 iptablesnat
-rw-r--r-- 1 root root  90K Nov 26 07:03 iptablessave
-rw-r--r-- 1 root root  36K Nov 26 07:03 netstat
-rw-r--r-- 1 root root 3.6K Nov 26 07:03 netstatistics
-rw-r--r-- 1 root root  756 Nov 26 07:03 …
```
> Added iptables, netstat, and cni configs to networking

- collection/rancher/v2.x/usage-collector/rancher2_usage_collector.sh
Output from testing (single node Rancher install):
```
$ ./rancher2_usage_collector.sh
Report run on Tue Nov 26 01:37:18 UTC 2019
Rancher version: v2.3.0
Rancher id: 2d1b5bbd-c6d9-4fd2-b0e6-f53441742adc
Cluster Id   Name            K8s Version     Provider                  Created                Nodes
c-5z2fp      customwithapi   v1.15.5         rancherKubernetesEngine   2019-11-25T23:59:11Z   10.0.7.11,10.0.7.12,10.0.7.10
c-lp85c      myk3s           v1.16.3-k3s.2   imported                  2019-11-26T01:36:30Z   <none>
local        local           v1.14.5-k3s.1   local                     2019-11-25T20:20:52Z   <none>
--------------------------------------------------------------------------------
Cluster: customwithapi (c-5z2fp)
Node Id          Address                  Role …
```
> Added node counts per cluster and per install

- .gitignore
- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Additional collection of OS related information:
- uname
- packages
- services
- lsblk
- cpuinfo
- top
- OS release information
- logs for systemd-based kubelet
Tested on Ubuntu 18.04, CentOS 7.6 and RancherOS 1.5.4.
Included an initial .gitignore file - for discussion on whether we need this.
> Additional OS information to the collection

- collection/rancher/v2.x/logs-collector/README.md
- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
- Break into functions to improve logic and readability
- Add detection of k3s and journald and log collect
- Check for available disk space
- Bring variables to top of script for visibility
- Add kubectl output for svc, nodes, pods, endpoints
- Remove tmp directory after collection
- Add timestamps to script output
- Add help menu
- Add [ipvsadm](https://github.com/rancherlabs/support-tools/issues/29) output
Tested on: CentOS 7.7, Ubuntu 18.04, OEL 7.7, Rancher OS 1.5.5
> Split into functions, add journald and k3s support

- extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
Cleanup script is missing the weave directory. This can cause issues when re-adding the node to clusters with weave.
> Added weave to the directories to remove

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
This line throws an error because you are trying a copy operation but then doing a redirect to the destination.    Removed the redirect to correct syntax error.
> Correct logic error on daemon.json copy

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
This makes the etcdctl commands work for etcd 3.4, avoiding the error as described in https://github.com/rancher/docs/pull/2514
> Correct etcdctl commands for etcd to support 3.4

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Adding `sed 's/token.*/token REDACTED/g'` in-order to redact the Rancher agent token for the Rancher agent logs.
> Adding sed to redact Rancher agent token

- extended-rancher-2-cleanup/README.md
- extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
This adding the flags `--flush-iptables` and `--flush-images` and changes the default behavior to not remove all images.
This is to help reduce the number of docker pulls by not removing all images.
> Adding flags to cleanup script

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
We collect wide output for kubectl get nodes if the runtime is docker, so updating k3s to reflect. yaml output is already mostly captured by nodesdescribe
> Change nodes collection for k3s to -o wide

- extended-rancher-2-cleanup/README.md
- extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
Prefer systemd, `/etc/init.d/docker` is often not created, use `systemctl` to restart docker
Corrected the incorrect flags in the usage
> Prefer systemd when restarting docker, correct flag usage

- bad-ingress-scanner/Dockerfile
- bad-ingress-scanner/README.md
- bad-ingress-scanner/bad-ingress.yaml
- bad-ingress-scanner/deployment.yaml
- bad-ingress-scanner/run.sh
This tool is designed to scan for misbehaving ingresses. An example being an ingress that was deployed referencing a non-extent SSL cert or an ingress with an empty/missing backend service.
> Adding bad ingress scanner script

- NGINX-to-pods-check/README.md
- NGINX-to-pods-check/check.sh
- NGINX-to-pods-check/example-deployment.yml
This script is designed to walk through all the ingresses in a cluster and test that it can curl the backend pods from the NGINX pods. This is mainly done to verify the overlay network is working along with checking the overall configuration.
Importing from https://github.com/mattmattox/NGINX-to-pods-check
> Adding NGINX-to-pods-check

- extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
These filesystems shouldn't be unmounted, tested on a downstream RKE node.
Previously would experience the below:
```
2021-03-24 23:06:41: Unmounting filesystems...
umount: /var/lib/kubelet: not mounted.
umount: /var/lib/rancher: not mounted.
```
In cases where these are actual filesystems this could cause `/var` to be used for k8s/docker/rancher.
> Remove unmount for kubelet and rancher

- collection/rancher/v2.x/logs-collector/README.md
- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Default nice/ionice to lowest priorities by default, override with `-p` to use the default priorities
Test on Ubuntu 20.04:
```bash
root@d-lab-w1:~# ps aux | grep logs.sh
root     3018969  0.2  0.1   9144  4132 pts/1    SN+  22:10   0:00 bash logs.sh
root     3019037  0.0  0.0   8164  2440 pts/0    SN+  22:10   0:00 grep --color=auto logs.sh
root@d-lab-w1:~# ionice -p 3018969
idle
root@d-lab-w1:~# ps -eo pid,ppid,ni,comm | grep 3018969
3018969 3002142  19 bash
3019095 3018969  19 bash
3019156 3018969  19 service
```
> Add lower nice and ionice priorities by default

- extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
To avoid errors, check for interface existence before delete.
Added weave-related interfaces
> Check interfaces before delete, add weave

- collection/rancher/v2.x/logs-collector/README.md
- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Added rke2 detection and collection, small general updates for consistency
Updated wording for 'runtime' to 'distribution' as this seemed more relevant (k3s/rke2 both use containerd etc). Tests so far have been done on Ubuntu 20.04.
> Add rke2 support to logs-collector

- cleanup-evicted-pods/README.md
- cleanup-evicted-pods/deploy.yaml
When a node starts to evict pods under disk pressure, the evicted pods are left behind. All the resources like volumes, IP, containers, etc will be cleaned up and delete. But the pod object will be left behind in "evicted" status. Per upstream this is [intentional](https://github.com/kubernetes/kubernetes/issues/54525#issuecomment-340035375)
> Cleanup evicted pods left behind after disk pressure

- collection/rancher/v2.x/rancher-pod-collector/README.md
- collection/rancher/v2.x/rancher-pod-collector/rancher-pod-collector.sh
This script is designed to capture debug logs from the Rancher Pods. It using the following workflow.
- Tries to figure kubeconfig access (It allow the user to override the kubeconfig then tries to see if it's running inside the cluster, then tries the current loaded kubeconfig, then tries k3s/docker exec.
- Captures some data about the cluster (nodes, k8s versions, svc, etc)
- Turns on debug logging in all Rancher pods (loglevel --set debug)
- Gives the user a pause message to give them time to reproduce the issue
- Turns off debug logging in all Rancher pods (loglevel --set info)
- Capture logs for all Rancher pods
- Archive output (using the same process as log collector)
> Adding rancher-pod-collector script

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
When ifconfig is not installed, we don't get error, dropped, overrun, etc. information. This adds the equivalent ip command to gather those stats.
> Add ip link show to get dropped packets, etc. stats

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Some airgapped client instances don't tag images, which causes Rancher Agent logs to not be collected. Added partial name to the grep for Rancher Agent to allow matching beyond "just" image tags.  Example docker ps -a output of agent that wouldn't be matched previously:
c1325a715fc3        911263d98471                                                                     "run.sh"                 6 days ago          Up 6 days                                     k8s_agent_cattle-node-agent-mn92x_cattle-system_2818e8e0-3706-44b8-a787-41ff3e7aa8c1_0
> Add pod name to RKE Rancher Agent lookup in log collector

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Added default rke2 agent/server logs for now, if there's a way to detect custom `--data-dir` locations it'd be great to accurately detect these.
> Add rke2 agent/server log directories

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Tested on two Ubuntu 20.04 nodes.
One with a custom data-dir (below), and defaults.
```bash
write-kubeconfig-mode: "0644"
data-dir: /opt/rke2
```
Related: https://github.com/rancherlabs/support-tools/issues/137
> Add detection for rke2 custom data-dir

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
There are new fleet namespaces included as part of the 2.6 release, cattle-fleet-system and cattle-fleet-local-system, that may need also to be captured during the log collecting process.
> Add new Rancher 2.6 fleet namespaces to the log collector

- cleanup-rancher-k8s-resources/cleanup.sh
- cleanup-rancher-k8s-resources/verify.sh
* This removes all resources in known namespaces so namespace removal does not get stuck on remaining resources in that namespace
* Also adds 2.5.x fleet namespace `fleet-system`
> Loop all resources in known namespaces

- cleanup-rancher-k8s-resources/cleanup.sh
As there can be a lot of events, it is unnecessary to loop through all and delete them one-by-one as the namespace deletion will delete all of them.
> Exclude events from cleanup

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Add `tigera-operator` & `calico-system` namespaces to collect Calico logs in RKE2 clusters
https://github.com/rancher/rke2-charts/blob/main/charts/rke2-calico/rke2-calico/v3.19.2-204/templates/tigera-operator/00-namespace-tigera-operator.yaml#L2-L4=
> Add tigera-operator namespace for RKE2

- bad-ingress-scanner/Dockerfile
- change-nodetemplate-owner/Dockerfile
The tag `latest` switched to `22.04` and it might be failing because of that, and it's not tested so better to pin and move over when it's tested/validated.
> Pin Ubuntu images until tested

- swiss-army-knife/README.md
- swiss-army-knife/admin-tools.yaml
- swiss-army-knife/overlaytest.sh
- swiss-army-knife/overlaytest.yaml
This PR adds some example deployments for swiss-army-knife with the two deployments being:
- Overlay test which is our standard overlaytest DaemonSet. This allows you to run `kubectl apply -f https://raw.githubusercontent.com/rancherlabs/support-tools/master/swiss-army-knife/deploy/overlaytest.yaml` instead of manually creating the file.
- Admin Tools which is an expansion of overlaytest but includes assigning cluster-admin permissions to the pod, runs the pods as privileged, moves the workload to kube-system (trying to avoid getting blocked by OPA), and mounts `/` on the host to `/rootfs` inside the pod to allow you to gain access to the node.
> Adding swiss-army-knife deployments

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
With new v2 provisioning in Rancher, the `rancher-system-agent` is used to begin initial connectivity to Rancher and execute the plan.
This PR includes the agent in the list of journalctl logs collected.
> Collect journalctl logs for rancher-system-agent

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Fixes a bug when passing the RKE2 runtime (`-r rke2`), this bypassed declaring the data-dir, causing issues running rke2/crictl/kubectl commands.
- Moved the data-dir handling to a separate function
- Call the function when the runtime flag is provided, and when it's being auto-detected
The PR doesn't change the current logic, but ensures a data-dir is always set.
Current logic:
- If no data-dir is provided (`-c /path`), set the default
- If config.yaml has a data-dir set, use that as a preference
> Handle RKE2 data-dir when passing runtime flag

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Add collection of `config.yaml` or files in the `config.yaml.d` directory (v2 provisioning).
Resolves: https://github.com/rancherlabs/support-tools/issues/188
> Add sanitised collection for RKE2 config.yaml

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
This prevents an aesthetic error when running the script if the Linux distro/version does not use systemd-resolved.
> Copy systemd-resolved conf only if the file exists

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
- Shift docker detection (rke) to the end of the conditions
- If `$DISTRO` is already set (k3s/rke2 detected) then don't test for docker (rke)
Resolves: https://github.com/rancherlabs/support-tools/issues/190
> Reorder distro detection

- extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
- Avoid removing `/opt/rke` by default
- Add flag `-s` / `--delete-snapshots`
- Added comments about usage
Resolves: https://github.com/rancherlabs/support-tools/issues/189
> Default to keeping etcd-snapshots during cleanup

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Revise the initial PR (https://github.com/rancherlabs/support-tools/pull/196), the condition did not correctly detect RKE.
Tested on RKE
```
root@d-rke-test1:~# bash logs.sh
2022-12-02 00:30:01: Created /tmp/tmp.NX243Wojpj
2022-12-02 00:30:01: Detecting available commands... renice ionoice
2022-12-02 00:30:01: Detecting OS... ubuntu 20.04
2022-12-02 00:30:01: Detecting k8s distribution... rke
2022-12-02 00:30:01: Detecting init type... systemd
2022-12-02 00:30:01: Using discovered data-dir...
2022-12-02 00:30:01: Collecting system info
2022-12-02 00:30:13: Collecting network info
2022-12-02 00:30:14: Collecting docker info
2022-12-02 00:30:18: Collecting rancher logs
2022-12-02 00:30:19: Collecting k8s component logs
2022-12-02 00:30:23: Collecting system pod logs
2022-12-02 00:30:40: …
```
> Revise condition for rke detection

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
We can use `-s` or `-e` to specify the start and end of logging. However, in many cases, it is the customer who does the logging, and `-s` and `-e` may be inconvenient. Therefore, this PR allows you to specify a start date and time.
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>
> Make start and end date configurable

- collection/rancher/v2.x/systems-information/systems_summary.sh
Recently had a case where the script was pulling a Rancher pod name that was evicted. Adding `--field-selector status.phase=Running` will prevent this.
Same case was initially opened because script was failing on RKE2 nodes. Workaround was to set KUBERNETES_PORT to any value. Added logic to check for RKE2 nodes to prevent issue in the future.
> Add check for RKE2 and running Rancher pods

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
At Japanese environment (`LANG=ja_JP.UTF-8`), dmesg log shows trailing Japanese characters.
```
[木  1月 26 08:05:48 2023] BIOS-provided physical RAM map:
```
This patch fixes it to English.
```
[Thu Jan 26 08:05:48 2023] BIOS-provided physical RAM map:
```
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>
> Use English at non English environment

- remove-webhook/README.md
- remove-webhook/remove-webhook.sh
Rancher webhook is now in downstream clusters as of 2.7.2 This can cause issues on rollback to earlier versions, so a script was created to help delete these webhooks
> Adding script to remove rancher-webhook

- how-to-retrieve-kubeconfig-from-custom-cluster/README.md
- how-to-retrieve-kubeconfig-from-custom-cluster/rke-node-kubeconfig.sh
- Update README to handle new container image label (non-jq example)
- Update wording to cover any RKE1 cluster, add option of using ACE, improve readability
> Update kubeconfig how-to

- LICENSE
Adding the Apache License to cover our tools and scripts. NOTE: This is the same license Rancher is published under.
> Adding apache license to match rancher/rancher

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Tested on RKE2
```
-rw-r--r-- root/root                      3832 2023-08-31 02:38 ./rke2/pod-manifests/cloud-controller-manager.yaml
-rw-r--r-- root/root                      3080 2023-08-31 02:38 ./rke2/pod-manifests/kube-scheduler.yaml
-rw-r--r-- root/root                      9681 2023-08-31 02:38 ./rke2/pod-manifests/kube-apiserver.yaml
-rw-r--r-- root/root                      6251 2023-08-31 02:38 ./rke2/pod-manifests/kube-controller-manager.yaml
-rw-r--r-- root/root                      3361 2023-08-31 02:36 ./rke2/pod-manifests/etcd.yaml
-rw-r--r-- root/root                      2525 2023-08-31 02:38 ./rke2/pod-manifests/kube-proxy.yaml
```
Resolves: https://github.com/rancherlabs/support-tools/issues/234
> Add static pod manifests for RKE2

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Resolves: https://github.com/rancherlabs/support-tools/issues/226
Retrieves the object listing for networkpolicies in all namespaces
Tested on RKE2 and k3s
> Add networkpolicy listing to log collection

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Tested on RKE2 and k3s where the changes apply.
The etcd keys are not included in the collection of config.yaml
Resolves: https://github.com/rancherlabs/support-tools/issues/235
> Sanitise s3 keys, collect sanitised config for k3s

- fleet-delete-cluster-registration/README.md
- fleet-delete-cluster-registration/delete_old_resources.sh
This is a cleanup script to work around a known Fleet bug whereby patching a downstream cluster, for instance when re-deploying a Fleet agent in such a cluster, causes new resources to be created without obsolete resources being deleted. Ultimately, this clutters the upstream cluster.
This script retrieves all cluster registration resources, orders them by cluster then by creation timestamp, and deletes all but the youngest cluster registration for each cluster. This causes obsolete cluster registrations and their child resources to be deleted.
> Add cluster registration deletion script for Fleet

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Resolves: https://github.com/rancherlabs/support-tools/issues/253
Currently the k8s distro detection relies on $PATH to include the binaries, in such cases that the alternate directory is used this is often not in the $PATH and fails to detect the distro. To account for this these directories have been added to the logic.
Example from the RKE2 install script:
>   - INSTALL_RKE2_TAR_PREFIX
>     Installation prefix when using the tar installation method.
>     Default is /usr/local, unless /usr/local is read-only or has a dedicated mount point,
>     in which case /opt/rke2 is used instead.
> Add alternative binary install directories for rke2/k3s

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Limit files collected from /var/log to avoid large log collections when a long history of files is kept
Considered adding a flag for this, however, we already have several similar flags -- open to thoughts?
> Add default 7 day limit for var log files

- eks-upgrade-using-api/README.md
- eks-upgrade-using-api/eks-support.sh
- eks-upgrade-using-kubectl/README.md
- eks-upgrade-using-kubectl/eks-support.sh
Add new option to unset node groups as managed fields for imported EKS Cluster
Issue: https://github.com/rancher/eks-operator/issues/469
> Add new option to unset node groups as managed fields for EKS Cluster

- collection/rancher/v2.x/profile-collector/README.md
- collection/rancher/v2.x/profile-collector/continuous_profiling.sh
Fix help param comma separated instead of spaces 
should read `-p profile,goroutine,heap` instead of  `-p  profile goroutine heap`
> Fix help param comma separated

- NGINX-to-pods-check/check.sh
- NGINX-to-pods-check/example-deployment.yml
The Ingress apiVersion changed a while ago from extensions/v1beta1 to networking.k8s.io/v1. This introduced the need to make 3 changes:
- Adapted the Ingress in the examples YAML to the new apiVersion. 
- Corrected how to search for the serviceName, as now it is under service: name:
- Restricted the number of ports to curl 1. If there is more than 1 port, the script fails. This could be adapted and introduce another for loop for each port.
These changes are needed for the review of KB: [https://www.suse.com/support/kb/doc/?id=000020011](https://www.suse.com/support/kb/doc/?id=000020011)
> Adapted to the new apiVersion 

- collection/rancher/v2.x/profile-collector/README.md
- collection/rancher/v2.x/profile-collector/continuous_profiling.sh
Added a new variable and check to create a single tarball with all the profiles and data collected.
To test it:
with a kubeconfig for a local cluster run
`bash continuous_profiling.sh -s 5 -t 1`
with a kubeconfig for a DS cluster run:
`bash continuous_profiling.sh -a cattle-cluster-agent -t 1 -s 5`
When a sigkill is received the script will stop. The tarball with the data collected is generated at the same location as the script is running
> rfe: added collected data to a single tar ball

- fleet-secrets-bro-patch/README.md
- fleet-secrets-bro-patch/patch_gitrepo_secrets.sh
This PR helps to address this issue: https://github.com/rancher/rancher/issues/45812
Which is a follow up to: https://github.com/rancher/dashboard/issues/11211 
Which will be fixed in 2.9 when this PR merges: https://github.com/rancher/dashboard/pull/11209
> Add script to patch secrets used by Fleet GitRepos

- troubleshooting-scripts/determine-leader/rancher2_determine_leader.sh
Fix for https://github.com/rancherlabs/support-tools/issues/280
The earlier lock was configmapresourcelock, now it's been switched to leaseresourcelock, thus corrected the command.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go#L178
> fix for issue#280

- collection/rancher/v2.x/profile-collector/continuous_profiling.sh
This helps identifying the Rancher leader pod, among other things.
> continuous_profiling: also collect leases

- collection/rancher/v2.x/profile-collector/continuous_profiling.sh
This uses .txt for text files, .log for log files, and uniforms the file names to always use dashes as a separator for clarity.
> continuous_profiling: uniform file names and extensions

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
As Rancher-provisioned RKE2/k3s clusters will have a `../manifests/rancher` directory, the current `ls` won't recurse into the directory.
Adding `-R` to list the additional files
> List manifest and TLS directories recursively

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Improvements for RKE2 and logging to help troubleshoot collection issues where the distro is not detected
- Log the output from the collector to a file in the collection as it runs
- Small improvements to detecting rke2 directories
- Renamed detection function to `rke2-setup` as this was only used for rke2
- Renamed the `RKE2_DATA_DIR` var to match it's usage 
- Check the `50-rancher.yaml` file for a custom data-dir as well (future support in v2prov is coming for this)
Initial testing done on an RKE2 standalone cluster
> RKE2 data directory improvements

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
```sh
$ sudo ./rancherlogcollector.sh -d logs
2024-08-19 09:46:21: Created logs/tmp.Ix35lA1TJv
2024-08-19 09:46:21: Detecting available commands... renice ionoice
2024-08-19 09:46:21: Detecting OS... ubuntu 22.04
2024-08-19 09:46:21: Detecting k8s distribution... k3s
2024-08-19 09:46:21: Detecting init type... systemd
2024-08-19 09:46:21: Collecting system info
2024-08-19 09:46:28: Collecting network info
2024-08-19 09:46:28: Collecting provisioning info
2024-08-19 09:46:34: Collecting k3s info
2024-08-19 09:46:41: Collecting k3s cluster logs
2024-08-19 09:46:47: Collecting system pod logs
2024-08-19 09:46:56: Collecting k3s directory state
2024-08-19 09:46:56: Collecting k3s certificates
2024-08-19 09:46:56: Collecting k3s server certificates
2024-08-19 09:46:56: Collecting k3s etcd info …
```
> Fix failure on collector-output.log file not found

- how-to-retrieve-kubeconfig-from-custom-cluster/README.md
- how-to-retrieve-kubeconfig-from-custom-cluster/rke-node-kubeconfig.sh
Newer versions of Rancher/RKE have migrated the full-cluster-state ConfigMap to a Secret due to the following security advisory: [https://github.com/rancher/rke/security/advisories/GHSA-6gr4-52w6-vmqx](https://github.com/rancher/rke/security/advisories/GHSA-6gr4-52w6-vmqx)
This PR updates the script to retrieve the kubeconfig on RKE clusters when relying on the full-cluster-state object and works now on both the older (ConfigMap) and newer versions (Secret).
The corresponding README was also updated for the manual steps.
> Fixed RKE kubeconfig retrieval script for newer Rancher and RKE versions

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Fix  rke2-etcd function. The etcd container has been hardened and we can't run bash in it.
Resolves: https://github.com/rancherlabs/support-tools/issues/278
> Fix rke2-etcd function rancher2_logs_collector.sh

- windows-agent-strict-verify/README.md
- windows-agent-strict-verify/update-node.ps1
In certain circumstances, Windows nodes will not respect the agent TLS mode configured for the Rancher server. This will occur if the following two conditions are true 
+ The Windows node was provisioned on a version of Rancher older than 2.9.2 or 2.8.8
+ The Windows node is running a deprecated version of rke2 (i.e. any version _lower_ than v1.30.4, v1.29.8, v1.28.13, v1.27.16.)
Nodes which do not meet the above circumstances will be automatically upgraded by Rancher after Rancher has been upgraded.
This PR presents a process and PowerShell script that can be used to manually update existing Windows nodes which will not be automatically updated by Rancher. To follow this process, the user must have access to the `stv-aggregation` secret in the downstream cluster. This process must be …
> Add workaround for agent strict verify on existing Windows nodes

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Add two namespaces useful to collect logs on the local cluster - namespaces for the CAPI controller and rancher-backup
> Add resources-system and provisioning-capi-system into log collection

- windows-access-control-lists/README.md
This PR adds documentation and a script for updating Access Control Lists for important files written to Windows nodes. Starting with Rancher 2.9.3 and 2.8.9, these files will be automatically patched post upgrade and will be properly configured during initial provisioning of new nodes. Likewise, standalone RKE2 clusters running versions `1.31.0`, `1.30.2`, `1.29.6`, `1.28.11`, `1.27.15` or above will also properly configure ACLs during initial provisioning. 
However, if a user is unable to upgrade Rancher, or has provisioned standalone rke2 nodes using a version older than the above listed versions, the ACLs must be manually updated. The script included in this PR can be used for both standalone rke2 clusters and Rancher provisioned rke2 clusters.
> Add workaround for configuring ACLs on Windows nodes

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Resolves https://github.com/rancherlabs/support-tools/issues/312
Tested on RKE2 and k3s, simulated the kube-apiserver being unavailable with `iptables -I INPUT -p tcp --dport 6443 -j REJECT`
> Revert to /var/log/pods if kube-api is unavailable

- swiss-army-knife/admin-tools.yaml
Refactor admin-tools.yaml to establish a dedicated namespace for swiss-army-knife and update associated resources accordingly. Modify service account and daemon set to use the new namespace, and streamline role and role binding configurations. Additionally, include a new service resource for improved accessibility. And remove PSPs
Resolves https://github.com/rancherlabs/support-tools/issues/329
> Move admin-tools to it's own namespace and remove PSPs

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
This part of the code is not working, 
techo "Collecting rke2 etcd metrics"
ETCD_ENDPOINTS=$(grep -oE '\b([0-9]{1,3}\.){3}[0-9]{1,3}:2379\b' $TMPDIR/etcd/memberlist | uniq)
for ENDPOINT in ${ETCD_ENDPOINTS}
do
curl -sL --connect-timeout 5 --cacert ${ETCD_CACERT} --key ${ETCD_KEY} --cert ${ETCD_CERT} https://$ENDPOINT/metrics > $TMPDIR/etcd/etcd-metrics-$ENDPOINT.txt
done
The metrics by default are published on line listen-metrics-urls: in file
/var/lib/rancher/rke2/server/db/etcd/config
>  Fixing rke2-etcd metrics collection

- rancher-crd/enumerate-resources/README.md
- rancher-crd/enumerate-resources/rancher-resource-enumerator.sh
- `rancher-resource-enumerator` discovers all rancher-related CRD's (*.cattle.io) and enumerates the custom resources that currently exist in the cluster.
- Built in options to enumerate all custom resources `-a`, non-namespaced resources `-c`, or custom resources for a space-delimited list of specific namespaces `-n <namespace>`
> Created rancher-resource-enumerator script

- swiss-army-knife/README.md
- swiss-army-knife/admin-tools.yaml
- swiss-army-knife/overlaytest.sh
Refactor overlaytest.sh to enhance network overlay test to add DNS testing capabilities
- Added support for DNS checks via '--dns-check' argument (Off by default)
- Improved output messages for better clarity on test results
- Consolidated pod information retrieval in one command for efficiency
- Enhanced error handling for DNS resolution tests
> Adding DNS tests to overlay test as an optional check

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
- Harvester team suggest support to use this tool to collect the guest cluster infomation (usually rke2/k3s k8s) for investigation. The volumeattachment info would help us to know the volume status on that time.
> logs-collector: add volumeattachment CRDs

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
make the file search safe against word splitting and globbing.
> using find instead of ls for copying net.d config

- collection/rancher/v2.x/profile-collector/continuous_profiling.sh
missed the ${TMPDIR} so the file is generated but not collected
> <fix> missing dir for metrics collection

- collection/rancher/v2.x/profile-collector/continuous_profiling.sh
I have add a new parameter -l so one can increase the log level to trace, or even chose to be at info. The default option is still debug
./continuous_profiling.sh -l trace -p heap -s 5
./continuous_profiling.sh -l info -p heap -s 5
> enhancement add option to chose trace log

- collection/rancher/v2.x/supportability-review/README.md
Typo in flag: `--private-registry-secret-user` is incorrectly typed.
It should be: `--private-registry-secret-username`
Link to Code/Repo:
[GitHub Repo](https://github.com/rancher/supportability-review/blob/5edd6821794438528576ed6902cbdb92114e48b8/01_data_collection/collect_info_from_rancher_setup.py#L1156)
> Typo in flag --private-registry-secret-user

- collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
With broad adoption of NFT backend in supported distro's, the `--wait` flag is no longer necessary.
Tested on RKE2/Ubuntu
> Remove wait for iptables NFT backend

- collection/rancher/v2.x/logs-collector/README.md
Add --backups option to the wget command, so the script is downloaded to rancher2_logs_collector.sh, even if it already exists. Also makes behaviour more consistent with the curl command
> Add --backups to wget

- collection/rancher/v2.x/systems-information-v2/README.md
The example provided is missing core data points.  Namely the "role" = "<none>".  
Without the role output to identify worker vs control-plane, the total count would be inaccurate.
I have included the output from my own lab/test environment which is Rancher (local), Harvester, RKE2 on Harvester, and a SUSE Observability cluster, all of which have the OS, Role, etc.. to do the analysis.
> Added output reflecting real clusters with complete data
