rancherlabs/support-tools

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Add istio-system namespace to list of system namespaces for which to collect inspects/logs
=> Add istio-system namespace

change-nodetemplate-owner/README.md
fixed URL to download script in instructions
=> fixed URL to download script in instructions

extended-rancher-2-cleanup/README.md, extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
Moving https://gist.github.com/superseb/06539c6dcd377e118d72bfefdd444f81 to Support-Tools
=> Adding Cleanup script

cluster-agent-tool/README.md
Updated README.md to include new URL and better instructions
=> Updated README.md to include new URL and better instructions

instant-fio-master/README.md, instant-fio-master/instant-fio-master.sh
initial commit of instant-fio-master
=> initial commit of instant-fio-master

rancher-single-tool/rancher-single-tool.sh
Script has been updated to fix grep issue found in the following support-kb PR:
https://github.com/rancherlabs/support-kb/pull/390
=> Updated script to use grep via an Ubuntu:18.04 container to fix ROS

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Added:
`if [ -d /var/lib/rancher/k3s/server ]; then` 
Around some of the server specific components (the directory does not exist on agents) 
This means that k3s-rancher is skipped for now  but agent nodes don't have kubeconfigs locally so will fail when trying to run that section anyway
Perhaps a kubeconfig generator might work in future?
These seem to have the necessary info to make one:
```
/var/lib/rancher/k3s/agent/etc/k3s-agent-load-balancer.json
/var/lib/rancher/k3s/agent/server-ca.crt
/etc/rancher/node/password
```
I might work on that next
---
Also this is my first contrib to a more publicly used script please test it (I didn't do much but it's best to be sure 😬 )
=> Added some ifs around the k3s server specifics

collection/rancher/v2.x/systems-information/systems_summary.sh
Tested on k3s, rke HA, and docker single environments.
=> Fixed Rancher System Summary Report on k3s. Fixed issue with settings CRD clashing with longhorn settings.

collection/rancher/v2.x/windows-log-collector/README.md, collection/rancher/v2.x/windows-log-collector/win-log-collect.ps1
Adding a new log collection script for Windows
=> initial commit of windows log collection script

charts/index.yaml
Switching from github.com to rancherlabs.github.io
=> Fixing repo url

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Added systemctl list-unit-files
=> systemctl list-unit-files

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
=> add iostat

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
add various ss commands for troubleshooting socket communications
=> add ss commands for socket troubleshooting

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Tested on an agent/server using Ubuntu 20.04
agent:
```bash
-rw-r--r-- 1 root root 18868 Aug  5 20:39 nodes
-rw-r--r-- 1 root root  5176 Aug  5 20:39 nodesdescribe
-rw-r--r-- 1 root root  1038 Aug  5 20:39 pods
-rw-r--r-- 1 root root   476 Aug  5 20:39 services
-rw-r--r-- 1 root root   502 Aug  5 20:39 version
```
server:
```bash
-rw-r--r-- 1 root root   254 Aug  5 20:39 configmaps
-rw-r--r-- 1 root root   538 Aug  5 20:39 endpoints
-rw-r--r-- 1 root root    19 Aug  5 20:39 events
-rw-r--r-- 1 root root   163 Aug  5 20:39 namespaces
-rw-r--r-- 1 root root 18868 Aug  5 20:39 nodes
-rw-r--r-- 1 root root  6086 Aug  5 20:39 nodesdescribe
-rw-r--r-- 1 root root  1038 Aug  5 20:39 pods
-rw-r--r-- 1 root root   476 Aug  5 20:39 services
-rw-r--r-- 1 root root   502 Aug  5 20:39 version
```
=> Add agent kubeconfig to allow agent nodes to run basic kubectl commands

troubleshooting-scripts/README, troubleshooting-scripts/kube-scheduler/find-leader.sh
This part of https://github.com/rancherlabs/support-kb/issues/824
=> Adding kube-scheduler leader script

extended-rancher-2-cleanup/README.md
This is just fixing a typo in the README
=> Fixing typo

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Add new namespaces for fleet and rancher controllers in v2.5
=> Add new namespaces to log collection

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Closes: https://github.com/rancherlabs/support-tools/issues/34
=> Add k3s server object output

cleanup-etcd-part-files/README.md, cleanup-etcd-part-files/alt-s3-sync.yaml, cleanup-etcd-part-files/delete-part-files.yaml
To workaround issue [gh-30662](https://github.com/rancher/rancher/issues/30662) please one of the following deployments.
=> Workaround ETCD Snapshots Part Files Issue

how-to-retrieve-kubeconfig-from-custom-cluster/README.md, how-to-retrieve-kubeconfig-from-custom-cluster/rke-node-kubeconfig.sh
Adding @superseb's script https://gist.github.com/superseb/b14ed3b5535f621ad3d2aa6a4cd6443b to support-tools
=> Adding retrieve kubeconfig script

.drone.yml
Adding the drone build file to start publishing our images in the rancher org.
=> Adding drone pipeline for testing

.drone.yml, etcd-tools/Dockerfile, etcd-tools/etcd-join.sh, etcd-tools/restore-etcd-single.sh
Migrating the docker image patrick0057/runlike to rancher/etcd-tools
=> Moving etcd-tools from patrick0057/runlike to rancher/etcd-tools

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
included cattle-monitoring-system and cattle-logging-system
=> add additional namespaces for monitoringv2 and loggingv2 in log collector script

etcd-tools/etcd-join.sh
=> Fix typo in etcd-tools script

collection/rancher/v2.x/rancher-pod-collector/rancher-pod-collector.sh
Update the level to `info` when disabling debug
=> Update disable-debug to set info log level

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Adds collection of sysstat / atop performance history
=> Add sysstat and atop collection

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Updated locations as per https://github.com/rancherlabs/support-tools/pull/133#discussion_r677183851
=> Add sa to logs collector stat collection

collection/rancher/v2.x/windows-log-collector/win-log-collect.ps1
This updates the Windows Log Collector with the updated script from Ross.
Source: https://raw.githubusercontent.com/rosskirkpat/windows-scripts/main/windows-log-collect.ps1?token=ANI7ZWZ6Z43SLNWJKK53KYDBJYOPU
=> Update Windows Log Collector with v2 from Ross

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Fixes https://github.com/rancherlabs/support-tools/issues/144
=> Add pidstat output

.drone.yml
Fixing https://github.com/rancherlabs/support-tools/issues/151
=> Adding metadata-syncer to the drone pipeline

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
=> Add nf_table collection

cleanup-rancher-k8s-resources/cleanup.sh
Reverts rancherlabs/support-tools#159
=> Revert "Make cleanup k8s compatible for non GNU sed"

.drone.yml
Build hasnt worked for the past x times and it is going to be replaced according to @mattmattox
=> Remove system-info as no longer needed

README.md
Added some warning text to the README.
=> adding warning text to README

swiss-army-knife/README.md
https://github.com/rancherlabs/support-tools/issues/176
=> Update swiss-army-knife README.md

rotate-tokens/rotate-tokens.sh
Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>
=> Add rotate-tokens script

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Tested on Ubuntu 20.04 + rke2-server
Resolves: https://github.com/rancherlabs/support-tools/issues/186
=> Add containerd log, fix newline in output

collection/rancher/v2.x/logs-collector/README.md, collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Signed-off-by: Masashi Honma <masashi.honma@gmail.com>
=> Make end date configurable

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Reverts rancherlabs/support-tools#196
=> Revert "Reorder distro detection"

collection/rancher/v2.x/logs-collector/README.md
Proposed changes:
- Match notes from KB article and cover use case of commonly used flag (`-d`)
- Add options for retrieving the script (wget/curl), provide one-liner approach
- Reduce steps, chmod is not necessary when run with `bash ...`
=> Update logs README

eks-upgrade-using-kubectl/eks-support.sh
This change fixes a bug where the script didn't use the kubeconfig file supplied via the flag. Instead it just picked up the default kubeconfig.
Additional checks have been added on upgrade to ensure the correct driver/provider is being used for a cluster.
This also changes the `list` command to better filter kev1 & kev2 clusters.
=> fix: ignore kubeconfig flag

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Resolves: https://github.com/rancherlabs/support-tools/issues/192
Tested on RKE2
=> Create child directory when archiving log collection

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Tested on each distribution, the `../etcd/etcd-metrics*` files have the expected output
Resolves: https://github.com/rancherlabs/support-tools/issues/130
=> Add etcd metrics for rke/rke2/k3s

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
tested with rke1 so far. needs further testing for k3s/rke2.
=> add provisioning related crds for offline debugging

extended-rancher-2-cleanup/README.md, extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
Tested on RKE1 worker/cp nodes
- Adjusted condition to default to flushing iptables and related wording in help/readme
- Updated wording for delete/clean for consistent wording
- Break up README wording for readability
Resolves: https://github.com/rancherlabs/support-tools/issues/227
=> Default to flushing iptables

adjust-downstream-webhook/README.md, adjust-downstream-webhook/adjust-downstream-webhook.sh
Rancher URL var has to be in a certain format
rancher-charts helm repo has to be added to a machine where this script is running from
=> Clarified Rancher URL var and pre-req

extended-rancher-2-cleanup/extended-cleanup-rancher2.sh
PR to test unmounting PVCs during cleanup
Resolves: https://github.com/rancherlabs/support-tools/issues/247
=> Umount pod filesystems, including non-tmpfs volumes

collection/rancher/v2.x/profile-collector/README.md, collection/rancher/v2.x/profile-collector/continuous_profiling.sh
Establishing a new script to collect Rancher golang profiles (https://pkg.go.dev/runtime/pprof)
=> Profile collector

collection/rancher/v2.x/systems-information-v2/README.md, collection/rancher/v2.x/systems-information-v2/deploy.yaml
This PR adds the new Systems Information v2 with the main difference that it runs as a pod now.
=> Add Rancher 2.x systems information script and deployment setup

collection/rancher/v2.x/systems-information-v2/README.md
=> Cleaning up cluster name

collection/rancher/v2.x/supportability-review/README.md
=> Updating supportability-review collection scripts (v0.71.0)

collection/rancher/v2.x/supportability-review/README.md, collection/rancher/v2.x/supportability-review/collect.sh
=> Updating supportability-review collection scripts (v0.77.1)

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Resolves: https://github.com/rancherlabs/support-tools/issues/326
Tested normal conditions on RKE2 and K3s nodes
=> Simplify and reorder preference of k8s distro detection

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Addressing SURE-9669, scrubbing sensitive files from cni config collection.
=> scrub cni configs

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
removed petname check from obfuscator preflight checks.
=> removing petname check

collection/rancher/v2.x/profile-collector/continuous_profiling.sh
we are removing the check done before for the profiles being passed with -p
so we can allow any custom profile needed
=> <enhancement>removing check to allow customer profiles

collection/rancher/v2.x/profile-collector/continuous_profiling.sh
I ended up creating a new branch instead of one from my fork
due to the fact that the fleet does not ship with curl or any tools on the container, we are changing the way of collecting profiles
now we create a port-forward for fleet on the case options
the we call the functions for rancher/cattle-cluster-agent 
or the fleet one for fleet-agent/controller
=> new funcs fleet and rancher collection

collection/rancher/v2.x/profile-collector/README.md
added a few examples so it is easier to first use the script
=> <enhancement> adding examples for profile collection

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
this works for rke2 clusters. fixes https://github.com/rancherlabs/support-tools/issues/365
=> add cilium network policies to log bundle if cilium is the cni

collection/rancher/v2.x/RBAC-role-collector/README.md, collection/rancher/v2.x/logs-collector/README.md, collection/rancher/v2.x/profile-collector/README.md, collection/rancher/v2.x/rancher-pod-collector/README.md, collection/rancher/v2.x/systems-information-v2/README.md, collection/rancher/v2.x/windows-log-collector/README.md
Update README's for a consistent structure and wording
=> Refresh collection READMEs

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Redact the calico token from containerd.log
=> Redact calico token from containerd.log

collection/longhorn/README.md, collection/longhorn/run.sh
- Introduced a script for collecting diagnostic information from Kubernetes clusters running Longhorn.
- Added detailed README documentation explaining usage, output structure, information collected, and privacy considerations.
=> Add Longhorn support bundle script and README

collection/rancher/v2.x/supportability-review/README.md
clarified and corrected spelling
=> update the post assessment heading

collection/rancher/v2.x/logs-collector/rancher2_logs_collector.sh
Resolves: #390 
Tested on RKE2 with RHEL 9.6
=> Add networkmanager configs
